- name: Home
  # width: slim
  center-vertically: true
  columns:
    - size: full
      widgets:
        - type: search
          autofocus: true

        - type: monitor
          cache: 1m
          title: Documents & Files (LAN)
          sites:
            - title: Linkwarden
              url: https://link.dlu.one/
              icon: di:linkwarden
            - title: Immich
              url: https://photos.dlu.one/
              icon: si:immich
            - title: Frigate
              url: https://frigate.mocha.dlu.one/
              icon: di:frigate

        - type: monitor
          cache: 1m
          title: Services (LAN)
          sites:
            - title: Router
              url: https://router.at.dlu.one/
              icon: si:opnsense
            - title: AdGuard Home
              url: https://ns2.at.dlu.one/
              icon: si:adguard
            - title: OpenMediaVault
              url: https://skuld.at.dlu.one/
              icon: si:openmediavault
            - title: Proxy Mocha
              url: https://proxy.mocha.dlu.one/
              icon: si:nginxproxymanager
            - title: Docker Mocha
              url: https://docker.mocha.dlu.one/
              icon: si:portainer

        - type: bookmarks
          groups:
            - title: General
              links:
                - title: Github
                  url: https://github.com/
            - title: Entertainment
              links:
                - title: YouTube
                  url: https://www.youtube.com/
                - title: Crunchyroll
                  url: https://www.crunchyroll.com/
            - title: Utils
              links:
                - title: Merry Sky
                  url: https://merrysky.net/
                - title: Proxmox Scripts
                  url: https://community-scripts.github.io/ProxmoxVE/scripts
