- name: Home
  # width: slim
  center-vertically: true
  columns:
    - size: full
      widgets:
        - type: search
          autofocus: true

        - type: monitor
          cache: 1m
          title: Media, Docs, Files (LAN)
          sites:
            - title: Linkwarden
              url: https://link.dlu.one/
              icon: /assets/icons/linkwarden.webp
            - title: Immich
              url: https://photos.dlu.one/
              icon: /assets/icons/immich.svg
            - title: Ollama WebUI
              url: https://ai.mocha.dlu.one/
              icon: /assets/icons/ollama.svg
            - title: Windmill
              url: http://senku.at.dlu.one
              icon: /assets/icons/windmill.svg
            - title: Frigate
              url: https://frigate.mocha.dlu.one/
              icon: /assets/icons/frigate.svg
            - title: Frontcam
              url: https://porta.mocha.dlu.one
              icon: /assets/icons/foscam.webp
              alt-status-codes:
                - 403
                - 401

        - type: monitor
          cache: 1m
          title: Services (LAN)
          sites:
            - title: Router
              url: https://router.at.dlu.one/
              icon: /assets/icons/opnsense.svg
            - title: Zelda
              url: https://zelda.at.dlu.one:8006/
              icon: /assets/icons/proxmox.svg
            - title: AdGuard Home
              url: https://ns2.at.dlu.one/
              icon: /assets/icons/adguard-home.svg
            - title: Beszel Monitor
              url: https://monitor.mocha.dlu.one/
              icon: /assets/icons/beszel.svg
            - title: Proxy Mocha
              url: https://proxy.mocha.dlu.one/
              icon: /assets/icons/nginx-proxy-manager.svg
            - title: Docker Mocha
              url: https://docker.mocha.dlu.one/
              icon: /assets/icons/portainer.svg

        - type: bookmarks
          groups:
            - title: General
              links:
                - title: Github
                  url: https://github.com/
                - title: YouTube Music
                  url: https://music.youtube.com
            - title: Entertainment
              links:
                - title: YouTube
                  url: https://www.youtube.com/
                - title: Crunchyroll
                  url: https://www.crunchyroll.com/
            - title: Utils
              links:
                - title: Merry Sky
                  url: https://merrysky.net/
                - title: Proxmox Scripts
                  url: https://community-scripts.github.io/ProxmoxVE/scripts
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: sunday

        - type: weather
          location: Rio de Janeiro, Brazil
          units: metric
          hour-format: 24h
