- name: News
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: rss
          limit: 20
          collapse-after: 10
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
              title: selfh.st
            - url: https://ciechanow.ski/atom.xml
            - url: https://www.joshwcomeau.com/rss.xml
              title: Josh Comeau
            - url: https://samwho.dev/rss.xml
            - url: https://ishadeed.com/feed.xml
              title: Ahmad Shadeed
            - url: https://terminaltrove.com/totw.xml
              title: Terminal Trove

    - size: full
      widgets:
        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters

        - type: videos
          channels:
            - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
            - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
            - UCsBjURrPoezykLs9EqgamOA # Fireship
            - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
            - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

        - type: group
          widgets:
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true

    - size: small
      widgets:
        - type: weather
          location: Rio de Janeiro, Brazil
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true

        - type: markets
          # The link to go to when clicking on the symbol in the UI,
          # {SYMBOL} will be substituded with the symbol for each market
          symbol-link-template: https://www.tradingview.com/symbols/{SYMBOL}/news
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: NVDA
              name: NVIDIA
            - symbol: AAPL
              name: Apple
            - symbol: MSFT
              name: Microsoft
            - symbol: ^BVSP
              name: Ibovespa
              symbol-link: https://www.tradingview.com/symbols/BMFBOVESPA-IBOV/news
            - symbol: MXRF11.SA
              name: Maxi Renda FII
              symbol-link: https://www.tradingview.com/symbols/BMFBOVESPA-MXRF11/news
            - symbol: AUVP11.SA
              name: AUVP11 ETF
              symbol-link: https://www.tradingview.com/symbols/BMFBOVESPA-AUVP11/news

        - type: releases
          cache: 1d
          # Read-only public token, set as GITHUB_TOKEN in the Portainer stack env
          token: ${GITHUB_TOKEN}
          repositories:
            - glanceapp/glance
            # mocha
            - immich-app/immich
            - linkwarden/linkwarden
            - crocodilestick/Calibre-Web-Automated
            - FreshRSS/FreshRSS
            - henrygd/beszel
            - NginxProxyManager/nginx-proxy-manager
            - portainer/portainer
            # zelda LXCs
            - blakeblackshear/frigate
            - AlexxIT/go2rtc
            - paperless-ngx/paperless-ngx
            - sbs20/scanservjs
            - syncthing/syncthing
            - AdguardTeam/AdGuardHome
            - gitlab:crafty-controller/crafty-4
            - clidey/whodb
            - vrana/adminer
