- name: Services
  # width: slim
  center-vertically: true
  columns:
    - size: full
      widgets:
        - type: split-column
          max-columns: 2
          widgets:
            - type: monitor
              cache: 1m
              title: Essentials (LAN)
              sites:
                - title: Router
                  url: https://router.at.dlu.one/
                  icon: /assets/icons/opnsense.svg
                - title: Zelda
                  url: https://zelda.at.dlu.one:8006/
                  icon: /assets/icons/proxmox.svg
                - title: AdGuard Home
                  url: https://ns2.at.dlu.one/
                  icon: /assets/icons/adguard-home.svg
                - title: Beszel Monitor
                  url: https://monitor.mocha.dlu.one/
                  icon: /assets/icons/beszel.svg
                - title: Proxy Mocha
                  url: https://proxy.mocha.dlu.one/
                  icon: /assets/icons/nginx-proxy-manager.svg
                - title: Docker Mocha
                  url: https://docker.mocha.dlu.one/
                  icon: /assets/icons/portainer.svg

            - type: monitor
              cache: 10m
              title: Photos & Video (LAN)
              sites:
                - title: Immich
                  url: https://photos.dlu.one/
                  icon: /assets/icons/immich.svg
                - title: Frigate
                  url: https://frigate.mocha.dlu.one/
                  icon: /assets/icons/frigate.svg
                - title: go2rtc
                  url: https://go2rtc.mocha.dlu.one/
                  icon: si:go2rtc
                  alt-status-codes:
                    - 403
                    - 401
                - title: Jellyfin
                  url: http://media.at.dlu.one:8096/
                  icon: /assets/icons/jellyfin.svg
                - title: Frontcam
                  url: https://porta.mocha.dlu.one
                  icon: /assets/icons/foscam.webp
                  alt-status-codes:
                    - 403
                    - 401
                - title: OwnTone
                  url: http://skuld.at.dlu.one:3689/
                  icon: /assets/icons/owntone.svg

            - type: monitor
              cache: 10m
              title: Documents & Files (LAN)
              sites:
                - title: Linkwarden
                  url: https://link.dlu.one/
                  icon: /assets/icons/linkwarden.webp
                - title: Ollama WebUI
                  url: https://ai.mocha.dlu.one/
                  icon: /assets/icons/ollama.svg
                - title: Paperless
                  url: http://paperless.at.dlu.one:8000
                  icon: /assets/icons/paperless-ngx.svg
                - title: Skuld
                  url: https://skuld.at.dlu.one/
                  icon: /assets/icons/openmediavault.svg
                - title: Syncthing
                  url: https://syncthing.at.dlu.one:8384/
                  icon: /assets/icons/syncthing.svg
                  allow-insecure: true
                - title: Windmill
                  url: http://senku.at.dlu.one
                  icon: /assets/icons/windmill.svg
                - title: FreshRSS
                  url: https://rss.mocha.dlu.one
                  icon: /assets/icons/freshrss.svg

            - type: monitor
              cache: 1m
              title: Network (LAN)
              sites:
                - title: AptCacher
                  url: http://apt-cacher-ng.at.dlu.one:3142/acng-report.html
                  icon: /assets/icons/debian-linux.svg
                - title: MySpeed
                  url: http://myspeed.at.dlu.one:5216/
                  icon: /assets/icons/speedtest-tracker.webp
                - title: Home Assistant
                  url: https://haos.at.dlu.one
                  icon: /assets/icons/home-assistant.svg
